name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tfsec using Docker
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v "$(pwd)":/src \
            aquasec/tfsec:latest \
            /src \
            --soft-fail \
            --format sarif \
            --out /src/tfsec.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif

      - name: tfsec PR commenter
        if: github.event_name == 'pull_request'
        uses: tfsec/tfsec-pr-commenter-action@v1.3.1
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Terraform security scan Advanced
        if: github.event_name == 'pull_request'
        uses: triat/terraform-security-scan@v3.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tfsec_actions_comment: true
          tfsec_output_format: sarif
        continue-on-error: true
